name: Integration for arbitrum & polygon

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  integrate-mainnet:
    name: Run integrate test v2 on arbitrum and polygon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - from: darwinia
            to: polygon
          - from: arbitrum
            to: darwinia
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: install dependencies
        run: yarn install

      - name: run task
        env:
          ORMPIPE_LOG_LEVEL: debug
          ORMPIPE_SIGNER: ${{ secrets.ORMPIPE_SIGNER }}
        run: |
          scripts/ormpipe.sh integration \
            send-message-msgport \
            --from=${{ matrix.task.from }} \
            --to=${{ matrix.task.to }} \
